# Generated by Django 2.1 on 2018-08-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
