# Generated by Django 2.1 on 2018-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20180831_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blogapp.Tag', verbose_name='标签'),
        ),
    ]
