# Generated by Django 2.1 on 2018-08-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20180831_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blogapp.Tag', verbose_name='标签集合'),
        ),
    ]
